micronaut:
  application:
    name: micronaut
  server:
    thread-selection: auto
    netty:
      parent:
        threads: 25
vertx:
  pg:
    client:
      port: 5432
      host: postgres
      database: ba
      user: ba
      password: ba
      maxSize: 500
